export const flavoures= [
  "Vainilla",
  "Chocolate",
  "Frutilla",
  "Menta Granizada",
  "Limón",
  "Chocolate Split",
  "Dulce de Leche",
  "Café",
  "Cookies and Cream",
  "Pistacho",
  "Dulce de Leche Granizado",
  "Caramelo",
  "Banana Split",
  "Coco",
  "Chocolate Belga",
  "Chocolate Amargo",
  "Nutello",
  "Frutos del Bosque",
  "Tiramisú",
  "Ananá",
  "Mango",
  "Melón",
  "Sandía",
  "Frutilla a la crema",
  "Durazno",
  "Arándano",
  "Dulce de Leche Especial Sofo",
  "Lima y menta",
  "Chocolate Blanco",
  "Brownie",
  "Snickers",
  "Chocolate Patagónico",
  "Limón",
  "Mousse de Maracuya",
  "Lemon Pie",
  "Tramontana",
  "Dulce de Leche Mil Hojas",
  "After Ocho",
  "Maracuyá y kiwi",
  "Açaí",
  "Mandarina",
  "CheeseCake",
  "Super Dulce de Leche",
  "Dulce de Leche Bariloche",
  "Menta",
  "Snickers",
  "Maracuyá",
  "Lima y menta",
  "Chocolate Patagónico",
  "Limón",
  "Mousse de Maracuya",
  "Lemon Pie",
  "Tramontana",
  "Dulce de Leche Mil Hojas",
  "After Ocho",
  "Maracuyá y Kiwi",
];
  
  export const yearsOfProduction = [
    { title: "Year", value: "" },
    { title: "2015", value: "2015" },
    { title: "2016", value: "2016" },
    { title: "2017", value: "2017" },
    { title: "2018", value: "2018" },
    { title: "2019", value: "2019" },
    { title: "2020", value: "2020" },
    { title: "2021", value: "2021" },
    { title: "2022", value: "2022" },
    { title: "2023", value: "2023" },
  ];
  
  export const fuels = [
    {
      title: "Fuel",
      value: "",
    },
    {
      title: "Gas",
      value: "Gas",
    },
    {
      title: "Electricity",
      value: "Electricity",
    },
  ];
  
  export const footerLinks = [
    {
      title: "About",
      links: [
        { title: "How it works", url: "/" },
        { title: "Featured", url: "/" },
        { title: "Partnership", url: "/" },
        { title: "Bussiness Relation", url: "/" },
      ],
    },
    {
      title: "Company",
      links: [
        { title: "Events", url: "/" },
        { title: "Blog", url: "/" },
        { title: "Podcast", url: "/" },
        { title: "Invite a friend", url: "/" },
      ],
    },
    {
      title: "Socials",
      links: [
        { title: "Discord", url: "/" },
        { title: "Instagram", url: "/" },
        { title: "Twitter", url: "/" },
        { title: "Facebook", url: "/" },
      ],
    },
  ];